### PR TITLE
Handle non safe request through link

### PR DESCRIPTION
**Pull request by gquemener**
See the wiki: https://github.com/KnpLabs/KnpRadBundle/wiki/csrf-protected-links

### CODE REVIEW

**Comment by gquemener** [comment]
See #38 also

**Comment by docteurklein** [comment]
yeah, we removed it finally.

**Comment by gquemener** [comment]
mmh, not really, we renamed it to link_csrf which allows user to generate the csrf for the configured links_csrf intention

**Comment by gquemener** [comment]
but definitly should be html safe

**Comment by gquemener** [comment]
done in ca9ddf1f0c7e507754d142e78775a9f4131b046f

**Pull request merged**
