### PR TITLE
add data type guesser

### PR DESCRIPTION
**Pull request by docteurklein**
Use form data to guess which field type should be used.

### CODE REVIEW

**Comment by defrag** [comment]
After this was merged the $form = $this->createBoundObjectForm($enity, 'new'); will not use NewEntityType - it will find the matching default object creator first and i will create Form with all entity objects.

**Comment by docteurklein** [comment]
ok, i'll fix that. thanks!

**Comment by docteurklein** [comment]
@defrag can you explain a bit more what's your problem ? 
Even better, can you paste your code somewhere (for me to reproduce the problem).

**Comment by defrag** [comment]
@docteurklein For example i have NewProposalType. When i create createBoundObjectForm($entity,'new'), it works as expected and uses the NewProposalType. However after updating RadBundle after this merge, whenever i call createBoundObjectForm($entity,'new') i never get NewProposalType. Instead i get detault form with all fields.

**Comment by docteurklein** [comment]
ok. I'll look what's happening.

**Comment by docteurklein** [comment]
fixed.

**Comment by docteurklein** [comment]
@defrag can you verifiy that this commit bc1de6a fixes you problem ? thanks.

**Pull request merged**
