### PR TITLE
Refactor specs compatible 2.3

### PR DESCRIPTION
**Pull request by docteurklein**

### CODE REVIEW

**Comment by gquemener** [comment]
I see prophecies here. Well well!

**Comment by docteurklein** [comment]
only promices :)

**Comment by docteurklein** [comment]
BUT! I have a strange problem with phpspec and php 5.3.x:

```
        exception [exc:ReflectionException("Class spec\Knp\RadBundle\DataFixtures\ReferencanipulatorSpec does not have a constructor, so you cannot pass any constructor arguments")] has been thrown.
```

**Comment by gquemener** [comment]
`ReferencanipulatorSpec` ?

**Comment by gquemener** [comment]
Indeed it doesn't raise exception on php 5.4.9

**Comment by docteurklein** [comment]
any news for 5.3 @gquemener  ?

**Comment by gquemener** [comment]
Yep after 5 minutes of lib-dev installations, I've somehow removed /sbin/init... and reinstall my system.

Why is it so complicated to manage multiple version of php? I'll try again (with phpenv) later

**Comment by docteurklein** [comment]
holy unlucky DUDE! :( here is a pointer http://3v4l.org/DWjYT

between  5.3.0 - 5.3.3 it fails
btweene  5.3.4 - 5.5.0beta2  it passes.

**Comment by gquemener** [comment]
Indeed, it only fails in 5.3.3... from 5.3.4 it's ok

**Comment by docteurklein** [comment]
so we should upgrade phpspec to try catch exceptions

**Comment by gquemener** [comment]
Something's wrong in your example. Why doesn't it throw exception if php >=5.3.4? It should, shouldn't it?
No constructor + newInstanceArgs with args => ReflectionException

**Comment by gquemener** [comment]
And what are these arguments that it's trying to pass to a class that have no constructor??

**Comment by docteurklein** [comment]
empty array. It should use newInstance(); instead.

**Comment by docteurklein** [comment]
https://twitter.com/everzet/status/339052313836650496 and https://github.com/phpspec/phpspec/issues/131

**Comment by gquemener** [comment]
Simplicity :D

**Comment by lsmith77** [comment]
would really move to have 2.3 support in master for our liip rad edition

**Comment by docteurklein** [comment]
I'm waiting for phpspec/phpspec#132 to be merged to go further. Otherwise, it fails, or we have to increase the php version requirement.

**Comment by docteurklein** [comment]
finally putting this in branch 2.3 and develop. 2.2 branch will be still here for symfony 2.2 compat.

**Comment by docteurklein** [comment]
develop is now 2.3 only.

**Pull request merged**
