### PR TITLE
force usage of one rad bundle, with custom namespace but named App

### PR DESCRIPTION
**Pull request by docteurklein**

### CODE REVIEW

**Comment by QuingKhaos** [comment]
Why? Why only one bundle?

**Comment by gquemener** [comment]
AFAIR this was due to some file/class finding convention (like templates) which didn't work with multiple "App" bundles.

Don't know if it's still the case today though since the check has been removed from  https://github.com/KnpLabs/KnpRadBundle/blob/develop/DependencyInjection/Compiler/RegisterAppBundlePass.php

**Comment by docteurklein** [comment]
it's not the case anymore, see #131 and #122

**Comment by docteurklein** [comment]
@patkar the reason was to avoid a bundle jungle.

**Comment by QuingKhaos** [comment]
Haha, yeah, shame on me. The RAD Edition was fixed to `v2.3.1`. Changing to `~2.3` and it works.

**Pull request merged**
