### PR TITLE
Use mapped classes instead classFinder

### PR DESCRIPTION
**Pull request by aitboudad**

### CODE REVIEW

**Comment by everzet** [comment]
@Aitboudad you've broke the spec suite ;)

**Comment by gquemener** [comment]
First, thank for your contribution!

Unfortunately, the solution you provide will register entities in any bundle, even if not in App bundle.
So I think it's a problem as we voluntary limit radifiction to a single bundle.

Besides, the `PassConfig type` parameter gave to `$container->addCompilerPass(...)` might be worst discussing.

**Comment by aitboudad** [comment]
But the old solution add a repository for any entity defined in the folder Entity but if isn't mapped ??.
My solution will register only entities if is in App Bundle and valide mapped entity.
For the the PassConfig type I think using TYPE_AFTER_REMOVING will be ok.

What do you think @gquemener 

Anyway, I find the use of "classFinder" as a solution is not the best way :(.

**Comment by docteurklein** [comment]
@Aitboudad, indeed, we could check that the class we found in `src/App/Entity`  is also registered in doctrine, before creating a repository for it.

**Comment by docteurklein** [comment]
by the way, @gquemener this solution will only create repository services if the entity is contained in the rad bundle namespace. It actually might be a good idea.

**Comment by docteurklein** [comment]
if the test suite passes :)

**Comment by aitboudad** [comment]
I'm not familiar with PHPSpec :(,  how I can add spec for this line

```
$classes = $container->get('doctrine.orm.entity_manager')->getConfiguration()->getMetadataDriverImpl()->getAllClassNames();
```

**Comment by gquemener** [comment]
Something like

``` php
$container->get('doctrine.orm.entity_manager')->willReturn($entityManager);
$entityManager->getConfiguration()->willReturn($configuration);
$configuration->getMetadataDriverImpl()->willReturn($driverImpl);
$driverImpl->get->getAllClassNames()->willReturn(array(...));
```

But I'm thinking that this could be a design issue and might be moved to a `DoctrineClassFinder` class.
Then we could make a `ClassFinderInterface` and rename `ClassFinder` to `FileSystemClassFinder`.

The design issue is that the compiler pass knows to much about the entity manager is trying to access class names through many other objects.
http://en.wikipedia.org/wiki/Law_of_Demeter#In_object-oriented_programming

What do you think @docteurklein @everzet ?

**Comment by aitboudad** [comment]
oops test suite passes ;).

**Comment by aitboudad** [comment]
Are there any remarks ?

**Comment by docteurklein** [comment]
nope, ready to merge!

**Pull request merged**
