### PR TITLE
Fix composer warning

### PR DESCRIPTION
**Pull request by canni**
Fix for composer warning see: [announce](https://groups.google.com/forum/#!msg/composer-dev/fWIs3KocwoA/nU3aLko9LhQJ)

### CODE REVIEW

**Comment by konradpodgorski** [comment]
+1

Although this might create BC break

**Comment by stof** [comment]
I don't see why it would be a BC break: the skeleton is only used when creating a project. Thus, composer already uses this new location since at least 2 weeks (with a BC file in the old location for now). What would break things is using the old location after the removal of the BC file in composer, or using a really outdated composer phar (which would probably be broken anyway as it would be out of sync with packagist)

**Comment by konradpodgorski** [comment]
@stof 

You're right. I didn't notice it's inside skeleton directory

**Comment by maoueh** [comment]
Please, consider merging this as I needed to edit manually the files to make it work otherwise, the `generate-rad-project` script fails.

On a side note, maybe I should open another issue, this instruction from the website `php vendor/bin/generate-rad-project NAME_OF_PROJECT` (in the Installation section) is wrong as the script is a bash script.

It should probably be:

```
sh vendor/bin/generate-rad-project NAME_OF_PROJECT
./vendor/bin/generate-rad-project NAME_OF_PROJECT
```

Or this on Windows:

```
vendor/bin/generate-rad-project.bat NAME_OF_PROJECT
```

Regards,
Matt

**Pull request closed without merging**
