### PR TITLE
configure services to be disabled by compiler pass

### PR DESCRIPTION
**Pull request by docteurklein**

### CODE REVIEW

**Comment by docteurklein** [comment]
should close #93

**Comment by gquemener** [comment]
Yep it does the job

**Comment by docteurklein** [comment]
very generic stuff that could be potentially added to core?

**Comment by docteurklein** [comment]
@lsmith77  thoughts  for this compiler pass?

**Comment by lsmith77** [comment]
not sure how soon i will have time to test this out.

@colinfrei / @tobion did you guys have time to look at KnpRadBundle yet?

**Comment by docteurklein** [comment]
we could propose a feature addition to DependencyInjection component:

add an possible value of "on-invalid" option that would be "remove", in addition to "ignore" or "error".

**Pull request merged**
