### PR TITLE
set 'Knp\RadBundle\Doctrine\EntityRepository' as a default repository class

### PR DESCRIPTION
**Pull request by aitboudad**
set 'Knp\RadBundle\Doctrine\EntityRepository' as a default repository class instead of 'Doctrine\ORM\EntityRepository' for any entity.

I think it will be useful :)

### CODE REVIEW

**Comment by docteurklein** [comment]
better is to use DoctrineBundle configuration to change this value. I think it's better to configure the doctrine bundle than hardcore modifying this value in a compiler pass.

``` yaml

doctrine:
    orm:
        default_repository_class:  Doctrine\\ORM\\EntityRepository

```

We could provide this default value in `rad-edition`.

**Comment by gquemener** [comment]
:+1:

**Comment by aitboudad** [comment]
i think you are right but why you defined EntityRepository as abstract ???

**Comment by docteurklein** [comment]
generally you would override it. It would force you to create a custom repository class that could help to create appropriate methods there, instead of in the controllers. 

But, indeed, we could put this class as concrete. ping @everzet @gquemener  ?

**Comment by aitboudad** [comment]
@gquemener I just close this feature but I want to know if you are with  or against ?? 
Thanks.

**Comment by docteurklein** [comment]
I prefer configuring doctrine to do it for us :)

**Comment by aitboudad** [comment]
@docteurklein  hhh ok as you like  :+1: , for info it only apply if default_repository_class is empty.

see you soon

**Pull request closed without merging**
