### PR TITLE
[RFC] Introduce a new routing loader that permits extensibility.

### PR DESCRIPTION
**Pull request by docteurklein**
Example:

``` yaml

App:Registration:
    elements: [index, new, create]
    controller: app.controller.registration
    calendar: ~
    defaults:
        _format: html
        _resources:
            form: { expr: service('app.form.registration') }

App:Contact:
    elements: [new, create]
    controller: app.controller.contact
    defaults:
        _format: html
        _resources:
            form: { expr: service('app.form.contact') }

App:StaticContent:
    elements: [index, edit]
    controller: app.controller.static_content
    prefix: false
    methods: [GET]
    defaults:
        _format: html
        _resources:
            form: { expr: service('app.form.staticcontent') }
    edit:
        requirements: { id: '\w+' }
    homepage:
        pattern: /
        defaults:
            _controller: FrameworkBundle:Template:template
            template: 'App:StaticContent:homepage.html.twig'

    locale_switch:
        methods: [GET|POST]
        pattern: /switch-locale

    about:
        pattern: /about
        defaults:
            _controller: FrameworkBundle:Template:template
            template: 'App:StaticContent:about.html.twig'

    portfolio:
        pattern: /portfolio
        defaults:
            _controller: FrameworkBundle:Template:template
            template: 'App:StaticContent:portfolio.html.twig'

```

### CODE REVIEW

**Comment by Djeg** [comment]
:+1:

**Comment by docteurklein** [comment]
@Djeg  I know it's not cool since yout worked on smthg similar, but I like this approach, and it permits controller as a service.

**Comment by Djeg** [comment]
@docteurklein nop it's okay, i never had time to do it. And this implementation is good. Just one question, what's the key : **calendar** on the `App:Registration` ?

**Comment by docteurklein** [comment]
a custom route. Everything that is not `['parent', 'elements', 'pattern', 'prefix', 'controller', 'methods', 'defaults', 'requirements',]` is a custom route.

**Comment by Djeg** [comment]
@docteurklein can you fix tests for this branch. Should be great if i can use it ASAP ;)

**Comment by docteurklein** [comment]
i'll try, but no time now. I have some new fixes to push too

**Comment by docteurklein** [comment]
hey there, I just puhsed the latest changes I was talking about. What about merging ?

**Comment by docteurklein** [comment]
edit: nope, tests break.

**Comment by docteurklein** [comment]
fixed. merging.

**Pull request merged**
