### PR TITLE
[WIP] add a form upload extension

### PR DESCRIPTION
**Pull request by gquemener**
Rebased @docteurklein branch on develop and adding an option to override the upload path at the field level.

### CODE REVIEW

**Comment by docteurklein** [comment]
awesome!

**Comment by docteurklein** [comment]
let's wait CI

**Comment by docteurklein** [comment]
also: i'm not even sure it works IRL :)

**Comment by gquemener** [comment]
let's see then ^^

**Comment by gquemener** [comment]
Woo lots of fun stuffs here, mostly due to the fact that rad bundle is based on master of symfony, thus generating a lot of errors due to BC break introduced in latest version of it (like in https://github.com/KnpLabs/KnpRadBundle/commit/812efb061284397ce4c4a038245bbfe7fa19c185).

I suggest tagging/branching current develop branch to a specific version of symfony (same for MinkExtension).

Otherwise, RadBundle will not be compatible anymore with symfony 2.3 for example.

**Comment by docteurklein** [comment]
huh right! Right now I don't have time to do it, but if you tell me what to do, I'd be pleased to do it :)

**Comment by gquemener** [comment]
I don't know on which version of symfony the RadBundle develop branch is supposed to work, it certainly does not on symfony master.

So, first thing I'd suggest relying on latest stable versions of all the dependencies that are compatible with develop branch of rad bundle (right now, I only see 2 broken deps mink extension and symfony), tag a version accordingly and create a separate branch (I let you chose the numbering, following symfony's version might be a good idea).

Then, rely on symfony ~2.7 on the develop branch and use it to test unstable feature of the next version.

**Thinkin out loud**
It'd be awesome to grab automatically the latest compatible version of the KnpRadBundle depending on the version of symfony you've required.
I don't know how that's possible though.
It'd be awesome too to add symfony versions to the travis matrice build.

**Comment by docteurklein** [comment]
@gquemener agreed, as always. If you have time to modify the build matrix to test out symfony versions, it could help us to tag each version correctly.

**Comment by gquemener** [comment]
I'm closing it while fixing the travis build recipe => https://github.com/KnpLabs/KnpRadBundle/pull/205

**Pull request closed without merging**
