### PR TITLE
Fixed mail helper controller class

### PR DESCRIPTION
**Pull request by gquemener**
Current implem is trying to guess bundle class from the `Knp\RadBundle\Controller\Helper\Mailer` class which is always failing.

This fix allows to perform the class guessing against the current controller namespace.

### CODE REVIEW

**Comment by gquemener** [comment]
Ping @docteurklein

**Comment by docteurklein** [comment]
awesome thanks!

**Comment by gquemener** [comment]
Un p'tit tag c'est possible aussi stp?

**Comment by docteurklein** [comment]
oui je peux tagguer si tu veux.

**Comment by docteurklein** [comment]
taggué 2.6.1 avec tes 2 dernieres PR's

**Comment by gquemener** [comment]
Merci!

**Pull request merged**
