### PR TITLE
fix MissingViewHandler for 2.3

### PR DESCRIPTION
**Pull request by lsmith77**

### CODE REVIEW

**Comment by gquemener** [comment]
Thanks, could you update the specs please?

**Comment by docteurklein** [comment]
Wait, I already fixed this during the week end :) Let me push this please, with all the specs updated.

**Comment by docteurklein** [comment]
Sorry for that!

**Comment by docteurklein** [comment]
see #95

**Comment by lsmith77** [comment]
pfiff. thanks for fixing :-)

**Pull request closed without merging**
