### PR TITLE
Fix unexistent 'password' in change set

### PR DESCRIPTION
**Pull request by Djeg**

### CODE REVIEW

**Comment by gquemener** [comment]
Why hasn't it been merged?

Currently the PasswordHashListener is throwing exception when the password field is not present in the changeset (https://github.com/doctrine/doctrine2/blob/master/lib/Doctrine/ORM/Event/PreUpdateEventArgs.php#L130).
Does recomputing the changeset is enough to take into account the new password @Djeg ?

**Comment by gquemener** [comment]
FYI, this happens to me when I'm saving a first time an user with a null `$plainPassword` (`$password` is not computed and remains null then) and resaving it later with a fill-up `$plainPassword`.
The password field is in the changeset at the entity creation, but not at the update because for the uow it was null, and is still null.

In fact, I'm wondering how this listener can work once the entity has been persisted. As the password field should not be directly manipulated by the user, this field should never be present in the updates' changeset (and so the `PasswordHashListener` should always throw exception when modifying the plain password of a persisted entity). 

Only hack I've found so far is to manually change the user `$password` value before flushing the uow:

**Comment by gquemener** [comment]
This should be reopened IMO

**Comment by docteurklein** [comment]
@gquemener yes, the isue is not resolved, but I'm not sure we should mess with UoW changesets IMHO.
~~Indeed the plainPassword will not (and should not) be in the changeset.~~

**Comment by docteurklein** [comment]
nevermind my last sentence. We should be careful with manual recomputation of **all** Changesets.

maybe we should use the `(re)compute(SingleEntity)Changeset($meta, $user)` only.

**Comment by gquemener** [comment]
Mmmh that sound interrrrresting

**Comment by docteurklein** [comment]
but they are internal public methods, unfortunalty. It's messy.

**Pull request closed without merging**
