### PR TITLE
Remove $entity from flush method

### PR DESCRIPTION
**Pull request by Baachi**

### CODE REVIEW

**Comment by docteurklein** [comment]
+1

**Comment by gquemener** [comment]
What does it change?

**Comment by Baachi** [comment]
Currently it will throw a PHP notice. See doctrine/doctrine2#166

**Comment by gquemener** [comment]
Interesting... What notice?

**Comment by docteurklein** [comment]
The flush call with entity parameter will indeed fail, but **only** if the entity is about to be removed.

For all other cases, it's ok.

**Pull request merged**
