### PR TITLE
Returning `app` and `Resources` folders

### PR DESCRIPTION
**Pull request by everzet**
Removing `app` and `Resources` folders was most problematic change for most of the adopters.
Also, it could create usage problems with different Symfony2 bundles.

So, we're moving application resources back into `Resources` folder (inside application, of course) and renaming `config` folder to the `app` and `config/bundles` to `app/configs` (and it's still splitted bundle configs with sensible defaults, just different folder name). It's not really big change and though requires you to make 1 additional step during Controller -> View movement, compatibility is more important in this particular case.

So, if this PR will be merged, RAD project structure would looke like this:

``` bash
.
├── app
│   ├── config
│   │   ├── app.yml
│   │   ├── assetic.yml
│   │   ├── framework.yml
│   │   ├── knp_rad.yml
│   │   ├── monolog.yml
│   │   ├── security.yml
│   │   ├── swiftmailer.yml
│   │   ├── twig.yml
│   │   └── web_profiler.yml
│   ├── kernel.yml
│   └── routing
│       ├── all.yml
│       ├── dev.yml
│       ├── prod.yml
│       └── test.yml
├── src
│   └── Hello
│       ├── Controller
│       │   └── HelloController.php
│       └── Resources
│           ├── config
│           │   ├── routing.yml
│           │   └── services.yml
│           ├── public
│           │   ├── css
│           │   │   └── style.css
│           │   └── js
│           │       └── script.js
│           └── views
│               ├── Hello
│               │   └── index.html.twig
│               └── layout.html.twig
├── cache
├── logs
├── vendor
└── web
```

What do you think?

### CODE REVIEW

**Comment by ArlingtonHouse** [comment]
One of the best things about this version is moving the views higher in the directory.  It is extremely tedious to pick through the Resources folder time after time after time, just to make an edit to a twig view file.  I'd argue that this solves a problem with Symfony2, and that Sf2 should change, not the awesome RAD bundle!

**Comment by szymek** [comment]
+1

**Comment by everzet** [comment]
@ArlingtonHouse this is exactly reason why there were moved upper by me initially. So, let's listen feedback. We will let community decide on such hard questions.

@szymek on what?

**Comment by szymek** [comment]
@everzet on this whole PR

**Comment by awildeep** [comment]
I actually dislike this (I guess I'll play devils advocate).  
1. The filesystem structure of Symfony2 is currently overly verbose for most things.  
2. The ./app directory for SF2 is not really accurately named...   It is basically configs and bootstrapping.  Honestly it annoys me everytime I see it there.
3. @ArlingtonHouse makes a great point about the nested directories.  

Do you have any examples of code that is breaking?   Perhaps the problem lies in that code not being written properly?

**Comment by everzet** [comment]
@awildeep for example, there's `assets:install` command that internally appends `Resources/public` to the bundle path, there's `FrameworkBundle\TranslationsPass` (DIC compiler pass, that adds translation resources to the manager), that also appends `Resources/translations`. And different 3rd-party bundles could copy and abuse this even more :-/

**Comment by stof** [comment]
The good change here is that the web folder is again `%kernel.root_dir%/../web` meaning that bundle having such default value (AsseticBundle for instance) are still usable with their default config

**Comment by stof** [comment]
@awildeep the `app` folder in Symfony also allows overwriting templates at the project level. It is not only config files

**Comment by b00gizm** [comment]
Too bad :(

the original bundle structure was like the one of good ol' symfony1, combined with the good new stuff which Symfony2 offers.

I'm actually with @ArlingtonHouse - maybe it's Symfony's structure that is flawed.

**Comment by everzet** [comment]
@stof we could use `./config` as a `kernel.root_dir` too. It's not really a problem. And this PR isn't really a solution for that.

**Comment by everzet** [comment]
@b00giZm hey, it's not decided yet. All in your hands ;-) If users will not agree with such "coming back" - we'll just close this PR!

**Comment by ruian** [comment]
I think you did a good folder structure (i talk about the current one). why ? because we are not talking about a bundle structure (who follow bundle rules), this is an app (rad) structure and it has his own structure. if you think this structure is better don't change it.

**Comment by l3pp4rd** [comment]
I think its not the flaw making a more convenient and sensible structure, there will be always a lot of conservative opinions that this is wrong to change things, if we go back to such proposal, there won't be much left in time

**Comment by Seldaek** [comment]
I'm definitely +1 on these changes. It focuses on actually improving/cleaning up some things without breaking stuff for the sake of it. I still think stuff like `app/console` shouldn't be moved (mostly because of documentation/support issues), but this is already a big improvement compared to the original version.

**Comment by tentacode** [comment]
I'll go -1 on this I actually... simple is better. I'm seeing this as a new framework, even if it might sound a bit exagerated, it's kind of obvious people would have to change their code a bit to make it work.

**Comment by b00gizm** [comment]
I'm voting for an official fork and we'll call it "Knpfony".

Go for it, guys ;)

**Comment by naholyr** [comment]
So bad you have to do this because of some poorly written tasks :'(
I dislike this "src/Resources" folder: why the hell a binary resource should be melted into my code ? get out of my "src" please ><.

Nethertheless this is minor, and even if I :+1: @awildeep if it's for the sake of compatibility, you make the good choice.

**Comment by everzet** [comment]
@naholyr where did you saw `src/Resources` ? :-) I think you've totally misread this PR ;-)

**Comment by l3l0** [comment]
-1 for PR. I think Resources directory always be a little overwhelming in SE. Lets try make thing a little different in this edition. BTW ./sf and ./sft was confiusing to me but this is not the case here (./console is better IMO)

**Comment by everzet** [comment]
@l3l0 agree on `sf` vs `console`: #13. Thanks for pointing.

I've renamed it to `sf` because there already was `con...` stuff in root (`config` folder) and autocompletion didn't worked properly (required you to type more chars). But as now it'll be probably called `app` (just `config` => `app`, `Resources` fate isn't decided yet), it's not a problem anymore.

**Comment by ludofleury** [comment]
The tree is close to Symfony convention, it could be cool. Yet I think the Resource level is not needed for a Rad distribution.

**Comment by maxailloud** [comment]
-1 for this PR because we don't need an app directory to tell us that this is the directory of our application, we already knowing that. So I think it's useless.
Removing a hierarchy level like the Resources one is a good thing for me, less empty directory is better.

**Comment by everzet** [comment]
@ludofleury there's is no such thing as Symfony convention. There is bundles convention and standard edition structure. And application code of RAD edition could avoid any of those.

**Comment by ludofleury** [comment]
@everzet Yeah, sorry, was in a rush. So let me be clear : I don't see the point to add some directory level like Resource, App etc. As your ninja opinion, some (many ?) applications do not need to be "reusable". The KnpRad distro is a very good alternative to a Silex + Symfony Component. "Premature abstraction is the root of evil" no ? Starting with bundle structure may appear to follow this way ? If the developer know that the application won't evolve that much, let him use your simple tree structure, If it's a beginner let's just write a visible and explicit disclaimer.

**Comment by tameribrahim** [comment]
Even if the original structure is more RAD and Sf2 puts the folder structure decision in your own hand,But consistency and compatibility with Sf2 common conventions is better.
+1 for changes.

**Comment by heikokrebs** [comment]
+1 for the "common conventions"

**Comment by everzet** [comment]
@heikokrebs there's no such thing as "common convention". There's only implicit project structure agreement based on the fact, that there were only one distribution for a long time and there's [bundles convention](http://symfony.com/doc/current/cookbook/bundles/best_practices.html), which starts with:

> A bundle is a directory that has a well-defined structure and can host anything from classes to controllers and web resources. Even if bundles are very flexible, you should follow some best practices **if you want to distribute them**.

And we're talking only about application-related code in different Symfony2 edition here, which isn't intended to be distributed. At least not without additional effort (moving it into separate well defined bundle).

**Comment by ruian** [comment]
+1 for console

**Comment by willdurand** [comment]
+1 for reasons I gave on Twitter

**Comment by keymaster** [comment]
+1 for returning to existing Symfony2 structure.  

You need to balance the extra work fighting wtf incompatabilities vs. one click on a folder to go the extra level deep. 

Who wants the hassle of dealing with incompatabilities? RAD is supposed to make things faster and simpler, not introduce problems.

**Comment by datiecher** [comment]
+1 for sticking with Symfony2 SE structure.

**Comment by everzet** [comment]
I'm merging this PR. We'll fully explain why in our blog post later today.

**Comment by everzet** [comment]
Sorry for being little bit late, but here is it: http://knplabs.com/blog/knp-rad-bundle-feedback :-)

**Pull request merged**
