### PR TITLE
add more types of skeleton when views does not exist, based on action name

### PR DESCRIPTION
**Pull request by docteurklein**

### CODE REVIEW

**Comment by docteurklein** [comment]
ping @gquemener @everzet @Herzult

**Comment by gquemener** [comment]
Nice idea! What is the `verbatim` block?

**Comment by docteurklein** [comment]
`verbatim` is the same as `raw`. It doesn't interpet the twig inside.

**Comment by gquemener** [comment]
approved

**Comment by cursedcoder** [comment]
+1

**Comment by docteurklein** [comment]
the fuck @gquemener !? I love this gif, but where do you find that?

**Pull request merged**
