### PR TITLE
Update ACE and use twig highlighter

### PR DESCRIPTION
**Pull request by cursedcoder**
http://d.pr/i/B4VD

should I minimize js, or it's okay?

### CODE REVIEW

**Comment by docteurklein** [comment]
I think it's ok! PS: Why do we need the chrome theme?

**Comment by gquemener** [comment]
neat!

**Comment by cursedcoder** [comment]
@docteurklein maybe @Herzult knows? https://github.com/KnpLabs/KnpRadBundle/commit/08a53a3d462b6af2739975043ab99f351f7edb56

**Comment by Herzult** [comment]
Thank you, it's way better using the right syntax :)

**Pull request merged**
