### PR TITLE
Describe and prove auto detect features using behat

### PR DESCRIPTION
**Pull request by umpirsky**

### CODE REVIEW

**Comment by docteurklein** [comment]
is this ok to be merged ?

**Comment by umpirsky** [comment]
@docteurklein Unfortunatelly some steps are failing. I didn't manage to figure out why.

**Comment by docteurklein** [comment]
i'll merge it already, so I can rebase against feature/behat branch. is it ok for you ?

**Comment by umpirsky** [comment]
Sure ;)

**Pull request merged**
