### PR TITLE
Use method handleRequest to bind request to form

### PR DESCRIPTION
**Pull request by gquemener**

### CODE REVIEW

**Comment by docteurklein** [comment]
ho! that's indeed very important. How can we not see this break ? Thanks by the way!

**Comment by gquemener** [comment]
Because there are no functionnal tests I believe

**Comment by docteurklein** [comment]
yeah, it was more a rethoric question :)

**Comment by docteurklein** [comment]
would be great to do func tests on it.

**Comment by docteurklein** [comment]
and by "func", I mean "funk":

**Pull request merged**
