### PR TITLE
Used PSR4 instead of target-dir

### PR DESCRIPTION
**Pull request by gquemener**
target-dir is now deprecated (https://getcomposer.org/doc/04-schema.md#target-dir)

### CODE REVIEW

**Comment by docteurklein** [comment]
it seems it breaks autoloading (see travis).

**Comment by gquemener** [comment]
Could it be linked to the fact that composer.phar is outdated? I'm investigating ;)

**Comment by gquemener** [comment]
Yep it was linked to outdated composer version. There's still a problem with behat

**Comment by docteurklein** [comment]
maybe behat autoloader is messing with psr-4 ? even if i think it should not influence it :/

**Comment by gquemener** [comment]
No it's just that interface `Behat\Behat\Snippet\Context\TurnipSnippetsFriendlyInterface` really does not exist.

**Comment by docteurklein** [comment]
ha yes, we need to fix that :) it's fixed somewhere in another branch, but not yet merged.

**Comment by docteurklein** [comment]
first wins :)

**Comment by gquemener** [comment]
Is it ok for you to switch to stable minimum-stability?

**Comment by docteurklein** [comment]
sure. I don't know why it's not :)

**Comment by gquemener** [comment]
Behat 3 is still buggy buggy... https://travis-ci.org/KnpLabs/KnpRadBundle/jobs/18186093#L577

**Comment by docteurklein** [comment]
ouch

**Comment by ghost** [comment]
im pretty sure that psr-4 should work fine on travis without updating composer now

**Comment by docteurklein** [comment]
this PR has to be rebased. Let's split PSR-4 stuff and other unrelated things in separated PR's.

**Pull request closed without merging**
